const XLSX = require('xlsx');
const path = require('path');

const pastries = [
    { name: "Chicken Puff", price: 120, stock: 50 },
    { name: "Vegetable Samosa", price: 40, stock: 100 },
    { name: "Egg Bun", price: 70, stock: 60 },
    { name: "Fish Cutlet", price: 50, stock: 80 },
    { name: "Chocolate Roll", price: 150, stock: 40 },
    { name: "Cinnamon Roll", price: 180, stock: 30 },
    { name: "Apple Turnover", price: 200, stock: 25 },
    { name: "Sausage Roll", price: 110, stock: 70 },
    { name: "Meat Pie", price: 160, stock: 45 },
    { name: "Cream Bun", price: 80, stock: 55 },
    { name: "Jam Tart", price: 75, stock: 65 },
    { name: "Fruit Danish", price: 190, stock: 20 },
    { name: "Chocolate Eclair", price: 220, stock: 15 },
    { name: "Cheese Straws", price: 90, stock: 110 },
    { name: "Lemon Tart", price: 210, stock: 18 },
    { name: "Blueberry Muffin", price: 140, stock: 50 },
    { name: "Vanilla Cupcake", price: 120, stock: 45 },
    { name: "Red Velvet Brownie", price: 170, stock: 35 },
    { name: "Donut Glazed", price: 100, stock: 90 },
    { name: "Donut Chocolate", price: 110, stock: 85 },
    { name: "Beef Patty", price: 150, stock: 50 },
    { name: "Vegetable Roll", price: 95, stock: 75 },
    { name: "Prawn Puff", price: 180, stock: 30 },
    { name: "Spinach & Feta Roll", price: 160, stock: 40 },
    { name: "Caramel Brownie", price: 185, stock: 25 },
    { name: "Almond Croissant", price: 230, stock: 20 },
    { name: "Butter Croissant", price: 180, stock: 40 },
    { name: "Pain au Chocolat", price: 210, stock: 35 },
    { name: "Strawberry Shortcake", price: 250, stock: 15 },
    { name: "Pineapple Tart", price: 85, stock: 70 },
    { name: "Gingerbread Cookie", price: 90, stock: 120 },
    { name: "Oatmeal Raisin Cookie", price: 100, stock: 110 },
    { name: "Chocolate Chip Cookie", price: 110, stock: 100 },
    { name: "Pretzel Cinnamon", price: 150, stock: 50 },
    { name: "Pretzel Salted", price: 140, stock: 55 },
    { name: "Bagel Plain", price: 120, stock: 60 },
    { name: "Bagel Cream Cheese", price: 180, stock: 45 },
    { name: "Hot Cross Bun", price: 95, stock: 80 },
    { name: "Scone Plain", price: 130, stock: 50 },
    { name: "Scone Blueberry", price: 150, stock: 40 },
    { name: "Profiterole", price: 110, stock: 60 },
    { name: "Mille-feuille", price: 280, stock: 12 },
    { name: "Macaron Vanilla", price: 80, stock: 150 },
    { name: "Macaron Chocolate", price: 80, stock: 150 },
    { name: "Macaron Pistachio", price: 90, stock: 140 },
    { name: "Baguette French", price: 250, stock: 30 },
    { name: "Garlic Bread", price: 150, stock: 50 },
    { name: "Sesame Bun", price: 65, stock: 90 },
    { name: "Cheese Bun", price: 110, stock: 60 },
    { name: "Mutton Samosa", price: 85, stock: 75 },
    { name: "Tuna Puff", price: 140, stock: 45 },
    { name: "Chicken Mayo Bun", price: 130, stock: 50 },
    { name: "Hot Dog Roll", price: 160, stock: 40 },
    { name: "Mushroom Savoury", price: 145, stock: 35 },
    { name: "Asparagus Tart", price: 210, stock: 20 },
    { name: "Quiche Lorraine", price: 260, stock: 18 },
    { name: "Vegetable Quiche", price: 240, stock: 22 },
    { name: "Baklava", price: 190, stock: 60 },
    { name: "Cannoli", price: 220, stock: 30 },
    { name: "Tiramisu Cup", price: 300, stock: 20 },
    { name: "Panettone SL", price: 450, stock: 10 },
    { name: "Focaccia Herb", price: 350, stock: 15 },
    { name: "Ciabatta Loaf", price: 320, stock: 20 },
    { name: "Rye Bread", price: 280, stock: 25 },
    { name: "Multigrain Bun", price: 80, stock: 80 },
    { name: "Wholemeal Roll", price: 75, stock: 85 },
    { name: "Honey Glazed Bun", price: 90, stock: 70 },
    { name: "Peanut Butter Cookie", price: 120, stock: 90 },
    { name: "Shortbread Biscuit", price: 60, stock: 200 },
    { name: "Lamington", price: 170, stock: 40 },
    { name: "Victoria Sponge Slice", price: 250, stock: 25 },
    { name: "Carrot Cake Slice", price: 280, stock: 20 },
    { name: "Zucchini Bread", price: 310, stock: 15 },
    { name: "Banana Bread Slice", price: 150, stock: 40 },
    { name: "Pumpkin Muffin", price: 160, stock: 35 },
    { name: "Challah Bread", price: 400, stock: 12 },
    { name: "Brioche Bun", price: 110, stock: 60 },
    { name: "Stollen", price: 550, stock: 8 },
    { name: "Kugelhopf", price: 480, stock: 10 },
    { name: "Gugelhupf", price: 460, stock: 10 },
    { name: "Madeleine", price: 70, stock: 120 },
    { name: "Financier", price: 90, stock: 100 },
    { name: "Canelé", price: 180, stock: 40 },
    { name: "Palmier", price: 130, stock: 60 },
    { name: "Vol-au-vent", price: 150, stock: 50 },
    { name: "Puff Pastry Horn", price: 170, stock: 40 },
    { name: "Napoleons", price: 290, stock: 15 },
    { name: "Galette de Rois", price: 650, stock: 5 },
    { name: "Kouign-amann", price: 350, stock: 10 },
    { name: "Religieuse", price: 320, stock: 15 },
    { name: "Paris-Brest", price: 380, stock: 12 },
    { name: "Saint-Honoré", price: 420, stock: 10 },
    { name: "Gâteau Opéra", price: 450, stock: 8 },
    { name: "Fraisier", price: 400, stock: 12 },
    { name: "Meringue Nest", price: 110, stock: 60 },
    { name: "Pavlova Individual", price: 350, stock: 18 },
    { name: "Eton Mess Pot", price: 280, stock: 25 },
    { name: "Churro Cinnamon", price: 130, stock: 80 },
    { name: "Custard Pie", price: 180, stock: 30 },
    { name: "Rhubarb Crumble", price: 220, stock: 20 }
];

const data = pastries.map(p => ({
    "Product Name": p.name,
    "Price": p.price,
    "Stock": p.stock
}));

const ws = XLSX.utils.json_to_sheet(data);
const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Products");

const outputDir = path.join(__dirname, 'artifacts');
const outputPath = path.join(outputDir, '100_Pastry_Products_Import.xlsx');

// Ensure artifacts dir exists (in node environment this might fail if not in workspace)
// But I'll just write it to the current dir first and then move it if needed or just provide it.
XLSX.writeFile(wb, '100_Pastry_Products_Import.xlsx');
console.log('File generated: 100_Pastry_Products_Import.xlsx');
